# Generated by Django 5.2.7 on 2025-10-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('direccion_fiscal', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('moneda_base', models.CharField(blank=True, max_length=10, null=True)),
                ('iva_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tasa_cambio_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empresa_config',
                'managed': True,
            },
        ),
    ]
