# Generated by Django 5.2.7 on 2025-10-26 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('es_empresa', models.BooleanField(blank=True, null=True)),
                ('empresa_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('puntos_fidelidad', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.usuarios')),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
    ]
