# Generated by Django 5.2.7 on 2025-11-09 18:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        # Usar SeparateDatabaseAndState para manejar tablas existentes
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Estas operaciones solo actualizan el estado de Django
                # sin tocar la base de datos (las tablas ya existen)
                migrations.CreateModel(
                    name='Venta',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('codigo_venta', models.CharField(editable=False, max_length=50, unique=True)),
                        ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=20)),
                        ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                        ('transaccion_id', models.CharField(blank=True, max_length=100, null=True)),
                        ('notas', models.TextField(blank=True, null=True)),
                        ('direccion_entrega', models.TextField(blank=True, null=True)),
                        ('tipo_entrega', models.CharField(choices=[('local', 'Retiro en Local'), ('domicilio', 'Entrega a Domicilio'), ('express', 'Entrega Express')], default='local', max_length=20)),
                        ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('cliente', models.ForeignKey(blank=True, db_column='cliente_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas', to='clients.clientes')),
                        ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas_realizadas', to='authentication.usuarios')),
                    ],
                    options={
                        'verbose_name': 'Venta',
                        'verbose_name_plural': 'Ventas',
                        'db_table': 'ventas',
                        'ordering': ['-fecha_venta'],
                        'managed': True,
                    },
                ),
                migrations.CreateModel(
                    name='VentaDetalle',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('cantidad', models.IntegerField()),
                        ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('descuento_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='products.productos')),
                        ('venta', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.venta')),
                    ],
                    options={
                        'verbose_name': 'Detalle de Venta',
                        'verbose_name_plural': 'Detalles de Venta',
                        'db_table': 'venta_detalles',
                        'managed': True,
                    },
                ),
            ],
            database_operations=[
                # No hacer nada en la base de datos para estas tablas
                # ya que ya existen
            ],
        ),
        # Crear solo la tabla Pago que no existe
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('qr', 'Código QR'), ('paypal', 'PayPal'), ('otro', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('tarjeta_ultimos_digitos', models.CharField(blank=True, max_length=4, null=True)),
                ('tarjeta_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_imagen_url', models.TextField(blank=True, null=True)),
                ('numero_transaccion', models.CharField(editable=False, max_length=100, unique=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sales.venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
                'managed': True,
            },
        ),
    ]
