# Generated by Django 5.2.7 on 2025-11-10 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('clients', '0001_initial'),
        ('sales', '0002_venta_pago_ventadetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada'), ('en_proceso', 'En Proceso')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('transferencia', 'Transferencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='NotificacionPush',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('venta', 'Venta Completada'), ('pago', 'Pago Recibido'), ('compra', 'Compra Realizada'), ('descuento', 'Descuento Disponible'), ('promocion', 'Promoción'), ('alerta', 'Alerta del Sistema'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Datos personalizados de la notificación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.IntegerField(default=0)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_push', to='clients.clientes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_push_sales', to='authentication.usuarios')),
                ('venta', models.ForeignKey(blank=True, help_text='Venta relacionada a la notificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_push', to='sales.venta')),
            ],
            options={
                'verbose_name': 'Notificación Push Ventas',
                'verbose_name_plural': 'Notificaciones Push Ventas',
                'db_table': 'notificaciones_push_sales',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
