# Generated by Django 5.2.7 on 2025-11-10 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('sales', '0003_alter_venta_estado_alter_venta_metodo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título personalizado del reporte', max_length=255)),
                ('tipo_reporte', models.CharField(choices=[('ventas', 'Reporte de Ventas'), ('productos', 'Reporte de Productos'), ('clientes', 'Reporte de Clientes'), ('estadisticas', 'Estadísticas Generales'), ('top_vendedores', 'Top Vendedores'), ('tendencias', 'Análisis de Tendencias')], default='ventas', max_length=50)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('filtros', models.JSONField(blank=True, default=dict, help_text='Filtros aplicados al generar reporte')),
                ('datos_reporte', models.JSONField(blank=True, default=dict, help_text='Datos del reporte en formato JSON')),
                ('resumen_texto', models.TextField(blank=True, help_text='Resumen en texto del reporte (IA)', null=True)),
                ('resumen_voz', models.FileField(blank=True, help_text='Resumen de audio del reporte (TTS)', null=True, upload_to='reportes/audio/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/pdf/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/excel/')),
                ('archivo_csv', models.FileField(blank=True, null=True, upload_to='reportes/csv/')),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error'), ('descargado', 'Descargado')], default='generando', max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('total_registros', models.IntegerField(default=0, help_text='Total de registros en el reporte')),
                ('tiempo_generacion', models.FloatField(default=0, help_text='Tiempo en segundos para generar el reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimaDescarga', models.DateTimeField(blank=True, null=True)),
                ('descargas', models.IntegerField(default=0, help_text='Número de descargas del reporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to='authentication.usuarios')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
                'ordering': ['-fecha_generacion'],
                'managed': True,
                'indexes': [models.Index(fields=['usuario', '-fecha_generacion'], name='reportes_usuario_e4272b_idx'), models.Index(fields=['tipo_reporte', 'estado'], name='reportes_tipo_re_5d8ddb_idx')],
            },
        ),
    ]
