# Generated by Django 5.2.7 on 2025-11-10 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('sales', '0004_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloIA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del modelo', max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('algoritmo', models.CharField(choices=[('linear_regression', 'Regresión Lineal'), ('arima', 'ARIMA'), ('exponential_smoothing', 'Suavización Exponencial'), ('prophet', 'Prophet'), ('random_forest', 'Random Forest'), ('neural_network', 'Red Neuronal')], default='linear_regression', max_length=50)),
                ('variable_objetivo', models.CharField(choices=[('ventas', 'Ventas'), ('cantidad_transacciones', 'Cantidad de Transacciones')], default='ventas', max_length=50)),
                ('estado', models.CharField(choices=[('entrenando', 'Entrenando'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('error', 'Error'), ('deprecado', 'Deprecado')], default='inactivo', max_length=20)),
                ('fecha_entrenamiento', models.DateTimeField(blank=True, help_text='Cuándo se entrenó el modelo', null=True)),
                ('datos_entrenamiento', models.IntegerField(default=0, help_text='Cantidad de registros usados para entrenar')),
                ('periodo_entrenamiento', models.CharField(choices=[('30d', 'Últimos 30 días'), ('90d', 'Últimos 90 días'), ('180d', 'Últimos 180 días'), ('1y', 'Último año')], default='90d', max_length=20)),
                ('precision', models.FloatField(default=0.0, help_text='Precisión del modelo (0-1)')),
                ('mae', models.FloatField(default=0.0, help_text='Mean Absolute Error')),
                ('rmse', models.FloatField(default=0.0, help_text='Root Mean Squared Error')),
                ('r_squared', models.FloatField(default=0.0, help_text='Coeficiente de determinación (R²)')),
                ('archivo_modelo', models.FileField(blank=True, help_text='Archivo pickle o joblib del modelo', null=True, upload_to='modelos_ia/')),
                ('parametros', models.JSONField(blank=True, default=dict, help_text='Parámetros del modelo')),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_ia_creados', to='authentication.usuarios')),
            ],
            options={
                'verbose_name': 'Modelo IA',
                'verbose_name_plural': 'Modelos IA',
                'db_table': 'modelos_ia',
                'ordering': ['-fecha_entrenamiento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('diaria', 'Predicción Diaria'), ('semanal', 'Predicción Semanal'), ('mensual', 'Predicción Mensual'), ('trimestral', 'Predicción Trimestral')], default='diaria', max_length=50)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True, help_text='Cuándo se generó la predicción')),
                ('fecha_inicio_periodo', models.DateField(help_text='Fecha de inicio del período predicho')),
                ('fecha_fin_periodo', models.DateField(help_text='Fecha de fin del período predicho')),
                ('valor_predicho', models.DecimalField(decimal_places=2, help_text='Valor predicho', max_digits=15)),
                ('intervalo_confianza_inferior', models.DecimalField(blank=True, decimal_places=2, help_text='Límite inferior del intervalo de confianza', max_digits=15, null=True)),
                ('intervalo_confianza_superior', models.DecimalField(blank=True, decimal_places=2, help_text='Límite superior del intervalo de confianza', max_digits=15, null=True)),
                ('valor_real', models.DecimalField(blank=True, decimal_places=2, help_text='Valor real del período (cuando se complete)', max_digits=15, null=True)),
                ('error_prediccion', models.DecimalField(blank=True, decimal_places=2, help_text='Error de predicción (real - predicho)', max_digits=15, null=True)),
                ('variables_utilizadas', models.JSONField(blank=True, default=dict)),
                ('datos_complementarios', models.JSONField(blank=True, default=dict)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='sales.modeloia')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'db_table': 'predicciones',
                'ordering': ['-fecha_prediccion'],
                'managed': True,
                'indexes': [models.Index(fields=['modelo', '-fecha_prediccion'], name='prediccione_modelo__00383d_idx'), models.Index(fields=['fecha_inicio_periodo', 'fecha_fin_periodo'], name='prediccione_fecha_i_3d4dbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromptFrecuente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del prompt frecuente', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de qué hace este prompt')),
                ('categoria', models.CharField(choices=[('ventas', 'Ventas'), ('productos', 'Productos'), ('clientes', 'Clientes'), ('estadisticas', 'Estadísticas'), ('analisis', 'Análisis'), ('prediccion', 'Predicción')], default='ventas', max_length=50)),
                ('tipo_reporte', models.CharField(choices=[('ventas', 'Reporte de Ventas'), ('productos', 'Reporte de Productos'), ('clientes', 'Reporte de Clientes'), ('estadisticas', 'Estadísticas Generales'), ('top_vendedores', 'Top Vendedores'), ('tendencias', 'Análisis de Tendencias')], max_length=50)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('filtros', models.JSONField(default=dict, help_text='Filtros predefinidos')),
                ('opciones', models.JSONField(blank=True, default=dict, help_text='Opciones adicionales (incluir_voz, agrupar_por, etc)')),
                ('veces_usado', models.IntegerField(default=0, help_text='Cantidad de veces utilizado')),
                ('ultima_utilizacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('favorito', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts_frecuentes', to='authentication.usuarios')),
            ],
            options={
                'verbose_name': 'Prompt Frecuente',
                'verbose_name_plural': 'Prompts Frecuentes',
                'db_table': 'prompts_frecuentes',
                'ordering': ['-favorito', '-veces_usado', '-ultima_utilizacion'],
                'managed': True,
                'indexes': [models.Index(fields=['usuario', 'activo'], name='prompts_fre_usuario_cbcdef_idx'), models.Index(fields=['categoria'], name='prompts_fre_categor_b94bed_idx')],
            },
        ),
    ]
