# Generated by Django 5.2.7 on 2025-11-13 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usuarios_id_alter_usuarios_rol'),
        ('products', '0001_initial'),
        ('sales', '0006_preferencianotificaciones_compartirreporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagada', 'Pagada'), ('confirmada', 'Confirmada'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, help_text='ID de sesión de Stripe', max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID del Payment Intent de Stripe', max_length=255, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pagada_en', models.DateTimeField(blank=True, null=True)),
                ('entregada_en', models.DateTimeField(blank=True, null=True)),
                ('carrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden', to='sales.cart')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='authentication.usuarios')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'ordenes',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productos')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
                'db_table': 'orden_items',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['usuario', '-created_at'], name='ordenes_usuario_2a7a45_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['estado'], name='ordenes_estado_c58784_idx'),
        ),
    ]
